### ISSUE TITLE
Arduino Mega PortH+

### ISSUE THREAD

**Issue by gueei** [felias-fogg/SoftI2CMaster#2]
On Arduino Mega, when using pins with Port H or above, the code cannot compile and giving error: 

    /SoftI2CMaster.h: In function 'boolean i2c_init()':
    /SoftI2CMaster.h:265: error: impossible constraint in 'asm'

It looks like the problem is coming from the _SFR_IO_ADDR(SXX_PORT). It works fine for any Port before G. Please help! Thanks!

**Comment by felias-fogg** [comment]
All ports above PORTG are only indirectly addressable, meaning that the code as it is won't work. Adapting it would mean that it becomes much slower. In a nutshell, PORTH and above won't be supported anytime soon. Sorry.
