### ISSUE TITLE
Is this lib support PMBus protocol ?

### ISSUE THREAD

**Issue by ejngnng** [felias-fogg/SoftI2CMaster#22]
I want to read values from a DC-DC device, the DC-DC device support PMBus protocol, can I use this lib?

**Comment by felias-fogg** [comment]
Well, this lib does not support "notifications" from the he slave to the host. It all depends on whether you want/need to use features that go beyond the I2C spec.

Best
Bernhard 

Von meinem iPad gesendet

**Comment by ejngnng** [comment]
@felias-fogg Thanks a lot
