### ISSUE TITLE
avr/io.h: No such file or directory

### ISSUE THREAD

**Issue by LilyGO** [felias-fogg/SoftI2CMaster#26]
Hi.
I was looking for this library at Google, but I did not find it

**Comment by felias-fogg** [comment]
avr/io.h is a header file that is part of the Arduino distribution, actually part of the gcc-avr tool-chain. I guess that you want to use SoftI2CMaster for a non-AVR MCU architecture. As I have written in the README file (3rd paragraph), there exists a different architectural neutral library: SlowSoftI2CMaster.
