### ISSUE TITLE
MCU hangs up when trying to use with an ATTINY828

### ISSUE THREAD

**Issue by MatCat** [felias-fogg/SoftI2CMaster#45]
Tried to use this library on an ATTINY828, hangs on  i2c_start function.

**Comment by felias-fogg** [comment]
I haven’t tested it on the ATtiny828 and never heard about it. This must be a recent MCU, right?

Hanging in the i2c_start procedure means usually that the two signal lines are tied to ground or floating. 

Best,
Bernhard

**Comment by MatCat** [comment]
Both I2C lines are pulled up with 4.7k
