### ISSUE TITLE
Please explain 3V and pull-up resistors

### ISSUE THREAD

**Issue by timkay** [felias-fogg/SoftI2CMaster#46]
Your excellent documentation says

> you do not want to use the implicitly enabled pull-up resistors because your devices are run with 3 volts

Please explain why it's a problem to use the built-in pull-up resistors when running at 3V?

**Comment by felias-fogg** [comment]
What I refer to is that the external devices are running on 3V (implicitly assuming that the system uses 5V as the system voltage). In this case, if you are using devices that are not 5V tolerant, you will destroy your device. 
This can be avoided by using pull-ups  that are tied to 3V.


Best,
Bernhard

Von meinem iPhone gesendet

**Comment by timkay** [comment]
Yeah, it was the assumption that the system is at 5V that I missed. Thanks!
