### ISSUE TITLE
Adding support for AVR 328PB

### ISSUE THREAD

**Issue by ablexOnGithub** [felias-fogg/SoftI2CMaster#48]
Is there a chance to add support for AVR ATMEGA 328PB. It is source compatible to the 328P from Arduino Pro Mini. But it adds one more hardware I2C, SPI and UART. When I switch the Board support to 328PB, SoftI2CMaster complains that it does not have any hardware I2C.

**Comment by felias-fogg** [comment]
Well, the complaint is definitely wrong. However, which I2C port would you support? One could also introduce another compile time constant.
