### ISSUE TITLE
SoftI2C @ ATtiny412  with megaTinyCore working?

### ISSUE THREAD

**Issue by SvenHi** [felias-fogg/SoftI2CMaster#51]
Hi,
thanks a lot for this great library. I tried to build it for ATtiny412 and have a build issue:

```
C:\Users\Sven\Documents\Arduino\libraries\SoftI2CMaster/SoftI2CMaster.h: In function 'i2c_read':
C:\Users\Sven\Documents\Arduino\libraries\SoftI2CMaster/SoftI2CMaster.h:854:6: error: impossible constraint in 'asm'

     );

      ^
```

I am not very familiar with asm gcc, so debugging will take a lot of time. Before I will try to start with it, It would be useful to know if you see any general blocking point for this target?

Not if I switch with same sketch to other target (eg. Arduino Nano) it builds with success.

Tanks a lot!

**Comment by felias-fogg** [comment]
Sorry, I do not have the slightest idea.
