### ISSUE TITLE
i2c ATtiny 84 not working

### ISSUE THREAD

**Issue by StonedEdge** [felias-fogg/SoftI2CMaster#56]
Hi there, 

I've been trying for a few hours to get your library working with my ATtiny84 to control a BQ power path IC (BQ24292i specifically) over i2c but it seems to be breaking my code every time I'm adding in the i2c related code chunks. I was wondering if you could help identify where my problem may lie? I've attached the code below. If it helps, I'm running the ATtiny84 with the internal 8Mhz internal oscillator. 

Best regards,
Ben 
[attiny84_stoned_dmcke5.txt](https://github.com/felias-fogg/SoftI2CMaster/files/6410678/attiny84_stoned_dmcke5.txt)

**Comment by felias-fogg** [comment]
Sorry, I do not have the time to debug other people's code. If you have a specific issue, you are welcome to post it here.
