### ISSUE TITLE
simpleSoftWire.ino Does Nothing aka Problem with Wire Wrapper

### ISSUE THREAD

**Issue by BlueNalgene** [felias-fogg/SoftI2CMaster#57]
## Observation

The example code ``simpleSoftWire.ino`` does not appear to communicate as stated.  The example code ``simpleSoftI2C.ino``, works fine.

## Expected

When running ``simpleSoftI2C.ino`` while connected to my oscilloscope, I see the expected digital signals for an I2C connection.  When I run ``simpleSoftWire.ino``, the signal remains grounded.

## Hardware/Software

Tested on Arduino Mega2560, Arduino Uno R3 Elegoo clone, and a custom Arduino Mega2560 board.  Compiled and run using Arduino IDE 1.8.13 and 1.8.5 (to see if it was related to Issue #53)

## Proposed Solution

If I add ``#define I2C_PULLUP 1`` to the Wire example, I see more correct peaks in the scope.  Was the example written with the unstated assumption that the user would have an external pullup only for the Wire variant?

**Comment by felias-fogg** [comment]
Well, I guess, I should include the same defines as in simpleSoftI2C in order to make it "comparable".
