### ISSUE TITLE
Not necessary warnings

### ISSUE THREAD

**Issue by weicher** [felias-fogg/SoftI2CMaster#7]
Hi!

I like your I2c library, but the [-Wunused-parameter] warnings are annoying.

These warnings are triggered because the compiler does not understand what you did ;-)

If you make a little change then these warnings disappear.

#ifndef _SOFTI2C_H
#define _SOFTI2C_H   1

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
----------------------------------------------------------------------------------
{
code
}
-----------------------------------------------------------------------------------
#pragma GCC diagnostic pop
#endif

Best Regards
Walter

**Comment by felias-fogg** [comment]
Thanks! Incorporated this already
