### ISSUE TITLE
Unable to create four objects to connect four modules with the same ID.

### ISSUE THREAD

**Issue by YasirShahazad** [felias-fogg/SoftI2CMaster#80]
Hello, I am currently developing a weight scale that utilizes four full birdge load cells for measuring the weight of an object. These load cells uses NAU7802 to read loadcell and have a fixed address 2A. My intention is to generate four objects from this library to interact with each of the load cells. However, I am encountering an issue where I am unable to create the desired four objects(4SDA, 4SCL) of the library.

**Comment by felias-fogg** [comment]
Let me cite from the readme file: [if] you want to use many different I2C buses, this library is not the right solution for you.
